[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = 'source ~/.local/share/dein/plugins/nightfox.vim'

[[plugins]]
repo = 'feline-nvim/feline.nvim'
hook_add = 'source ~/.local/share/dein/plugins/feline.lua'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = 'source ~/.local/share/dein/plugins/gitsigns.lua'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'source ~/.local/share/dein/plugins/startify.vim'

[[plugins]]
repo = 'nanozuki/tabby.nvim'
hook_add = 'source ~/.local/share/dein/plugins/tabby.lua'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = 'source ~/.local/share/dein/plugins/lspconfig.lua'

[[plugins]]
repo = 'ojroques/nvim-osc52'
hook_add = 'source ~/.local/share/dein/plugins/osc52.lua'

[[plugins]]
repo = 'vim-denops/denops.vim'
